# 
# Copyright IBM Corp. All Rights Reserved.
# 
# SPDX-License-Identifier: Apache-2.0
# 

version: '2'

networks:
  fabnet:

volumes:
  orderer.fabric.com:

services:

  orderer2.fabric.com:
    container_name: orderer2.fabric.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_RETRY_LONGINTERVAL=10s 
      - ORDERER_KAFKA_RETRY_LONGTOTAL=100s
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/fabric.com/orderers/orderer2.fabric.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/fabric.com/orderers/orderer2.fabric.com/tls/:/var/hyperledger/orderer/tls
      - orderer.fabric.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

    extra_hosts:
      - "kafka1:192.168.1.180"
      - "kafka2:192.168.1.181"
      - "kafka3:192.168.1.182"
      - "kafka4:192.168.1.183"
    networks:
      - fabnet
